[build]
    publish = "docs/blog"

[build.environment]
    HUGO_VERSION = "0.121.1"
    # HUGO_THEME = "repo"

[context.production]
    # command = "cd exampleSite && hugo --gc --themesDir ../.. -b ${URL}"
    command = "cd blog && hugo --gc --destination ../docs/blog -b ${HUGO_BASE_URL}"
    [context.production.environment]
        HUGO_ENV = "production"

[context.branch-deploy]
    # command = "cd exampleSite && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
    # command = "cd exampleSite && hugo --gc --themesDir ../.. -b ${DEPLOY_PRIME_URL}"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

        [plugins.inputs]
            # If it should show more verbose logs (optional, default = true)
            debug = true
            # Relative path to source directory in case you use Hugo's "--s" option
            # srcdir = "exampleSite"
