# Markdown renderer configuration
[goldmark.renderer]
unsafe = true

[tableOfContents]
ordered = false
startLevel = 1
endLevel = 3

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
