# Markdown renderer configuration
[goldmark.renderer]
unsafe = true

[tableOfContents]
ordered = false
startLevel = 3
endLevel = 5

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
tabWidth = 4
