# Configure main menu and social menu
[[main]]
identifier = "home"
name = "主页"
url = "/"
weight = 1

[main.params]
icon = "home"
newtab = false

[[main]]
identifier = "about"
name = "关于"
url = "/about"
weight = 10

[main.params]
icon = "info"
newtab = false



[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Jedore"

[social.params]
icon = "brand-github"

#[[social]]
#identifier = "twitter"
#name = "Twitter"
#url = "https://twitter.com"

#[social.params]
#icon = "brand-twitter"
