name: Python Mirrors
on:
  schedule:
    # update python mirror every midnight
    - cron: '0 0 * * *'

jobs:
  update-python-mirrors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
        with:
          python-version: '3.7'
      - run: python 

