name: Python Mirrors
on:
  schedule:
    # update python mirror every midnight
    - cron: '0 0 * * 6'

jobs:
  update-python-mirrors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-python
        with:
          python-version: '3.10'
          cache: 'pip'
          ref: 'main'
      - run: pip install -r requirements.txt
      - run: python scripts/test.py

